-- 함수 (NULL 처리)

-- NVL
SELECT EMPNO, ENAME, JOB, SAL, NVL(COMM * 12, 0) 연봉
FROM EMP
;


-- NVL2
SELECT EMPNO, ENAME, JOB, SAL, NVL2(COMM, COMM*12 ,0)
FROM EMP
;

-- NULLIF
SELECT EMPNO, ENAME, JOB, SAL, COMM, NULLIF(SAL, 800) AS "800은NULL로표시"
FROM EMP;

